---
title: "Kapitel 2"
author: "Elisa Bender"
date: "25 8 2018"
output: html_document
---
---
---
<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# Theoretischer Hintergrund und Forschungsstand
## Gravitationsmodelle

Mit Gravitationsmodellen (oder auch Interaktionsmodellen) sollen gesellschaftliche Besonderheiten in Korrespondenz zu Newton’s Gravitationsgesetz charakterisiert werden, „demnach wächst die Anziehungskraft zweier Massen mit deren Größe und sinkt mit dem Quadrat ihrer Entfernung“ [Bökemann]. Schon seit geraumer Zeit werden sie genutzt, um vor allem die Interaktionen zwischen Angebotsstandorten und ihren Konsumenten zu beschreiben. Bereits 1929 erörterte Reilly im „Gesetz der Einzelhandelsgravitation“, dass die Relation des Gewinns zweier Standorte gleichmäßig aus ihrer jeweiligen Attraktion und Entfernung zum Nachfrageort resultiert. Die Attraktivität eines Angebotsstandortes nehme dabei proportional mit dessen Population bzw. Angeboten zu [Reilly]. Ist die Attraktivität des Angebots hoch wirkt sie sich positiv auf die Entscheidung der Konsumenten aus, während eine zunehmende Entfernung weniger attraktiv ist und sich im Umkehrschluss negativ darauf auswirkt [Wood und Reynolds 2011 & Handbuch Handel…].

Sämtliche gravitationstheoretische Ansätze/Gravitationsmodelle thematisieren die Distanz zwischen Konsumenten und Angebotsstandorten und wie sich diese auf das Verhalten der Konsumenten auswirkt. Die verschiedenen Modelle unterscheiden sich jedoch in zwei Auffassungen. Die deterministischen Ansätze basieren auf der Annahme, dass eine Abgrenzung der Einzugsbereiche nur zwischen zwei Angebotsstandorten möglich ist. Jeder Nachfrageort wird dabei genau einem dieser Standorte zugewiesen. Dem gegenüber stehen die probabilistischen Ansätze. Diese berücksichtigen sowohl alle Angebotsstandorte als auch, dass Konsumenten in ihrer Entscheidung von unterschiedlichen Faktoren beeinflusst werden und sich nicht explizit für einen Angebotsstandort entscheiden [Die Analyse von Standorten und Einzugsbereichen & Einzugsbereiche von Arztpraxen und die Rolle der …].
Einen besonders wichtigen Beitrag (probabilistischen Ansatz) lieferte Huff (2.1.2) im Jahr (Jahr) mit seinem „Modell der Gelegenheitenpräferenz“ [Huff]. Dieses ist bis heute Grundlage vieler Untersuchungen und Arbeiten, wodurch sein ursprüngliches Modell im Laufe der Zeit kontinuierlich erweitert worden ist (siehe auch 2.2.3). 


### Huff’s Modell der Gelegenheitenpräferenz
Huff [HUFF] definiert sein Modell auf Grundlage von Einzugsbereichen, geographisch abgegrenzte Bereiche, die Angebote für die Konsumenten enthalten. Die Konsumenten selbst seien das zu betrachtende Objekt bei der Analyse von Einzugsbereichen. Man müsse die Gründe ihrer Handlungen verstehen, um das räumliche Verhalten der Konsumenten nachvollziehen zu können. Dabei haben zwei Variablen einen besonders großen Einfluss auf das Verhalten des Verbrauchers, so Huff. Zum Einen das Angebot: Je vielfältiger dieses ist, desto größer ist die Wahrscheinlichkeit für den Verbraucher, dass seine Bedürfnisse erfüllt werden. Dafür nimmt er auch weitere Wege in Kauf. Zum Anderen die Reisezeit: Neben der tatsächlichen Dauer der Anfahrt zum Angebotsstandort,  beinhaltet sie ebenfalls (indirekt) die erwarteten Reisekosten und Anstrengungen, die der Verbraucher für die Reise auf sich nehmen muss. Er ist dabei allerdings in seiner ihm zur Verfügung stehenden Zeit begrenzt. 

Die originale Wahrscheinlichkeitsberechnung, dass Verbraucher aus den umgebenen Einzugsbereichen zum Anbieterstandort reisen, lautet:
